name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the action daily at midnight.
  workflow_dispatch: # This allows you to run the workflow manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Sync changes
      run: |
        git remote add upstream ${{ github.event.repository.parent.ssh_url }}
        git fetch upstream
        git checkout main
        git merge upstream/main --strategy-option theirs --no-edit
        git push
